services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      CONNECTION_STRING: "Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USERNAME};Password=${DB_PASSWORD}"
      ISSUER: "https://localhost"
      AUDIENCE: "local-client"
      SECRETKEY: "N763+dpSr4rWDI0TjDmjC0zPZ516GR30+6ud1kZjJ48="
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      ALLOWED_INSIDE: ${ALLOWED_INSIDE}
      ALLOWED_OUTSIDE: ${ALLOWED_OUTSIDE}
    ports:
      - "5199:5199"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        VITE_REACT_APP_BACKEND_URL: http://localhost:5199
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${OUTSIDE_FRONTEND_PORT}:80"

volumes:
  pgdata:
  minio-data:
