version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./Markdown/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5199
    ports:
      - "5199:5199"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_REACT_APP_BACKEND_URL: http://backend:5199 # Передаем переменную как аргумент сборки для Vite
    ports:
      - "3000:80"
    depends_on:
      - backend
